version: '3.4'

services:
  gpuavailabilitychecker:
    image: gpuavailabilitychecker
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "gpuAvailabilityChecker.js"]
